# Generated by Django 3.2.9 on 2021-12-05 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrodoc', '0002_empleado_habilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('short_name', models.CharField(max_length=50, verbose_name='Nombre corto')),
            ],
            options={
                'verbose_name': 'secretaria',
                'verbose_name_plural': 'Secretaria de la institucion',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre completo')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('materia', models.CharField(blank=True, max_length=50, verbose_name='Materia')),
                ('avatar', models.ImageField(blank=True, upload_to='registro', verbose_name='Imagen')),
                ('administracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrodoc.administracion')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias de la Institucion',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre completo')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('avatar', models.ImageField(blank=True, upload_to='registro', verbose_name='Imagen')),
                ('administracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrodoc.administracion')),
            ],
            options={
                'verbose_name': 'NoDocente',
                'verbose_name_plural': 'NoDocentes',
            },
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='habilidad',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Habilidad',
        ),
    ]
