# Generated by Django 3.2.9 on 2021-12-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodoc', '0005_alter_docente_materia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['name'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterField(
            model_name='administracion',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='materia',
            field=models.CharField(blank=True, max_length=50, verbose_name='Materia'),
        ),
    ]
