# Generated by Django 3.2.9 on 2021-12-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodoc', '0006_auto_20211205_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['name'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materias de la institucion'},
        ),
        migrations.AlterField(
            model_name='materia',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
