# Generated by Django 3.2.9 on 2021-12-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrodoc', '0007_auto_20211205_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['name'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
    ]
